name: libirmin

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  rust:
    strategy:
      fail-fast: true
      matrix:
        os:
          #- macos-latest
          - ubuntu-latest
        ocaml-compiler:
          - 5.2.1
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/flakehub-cache-action@main


      - name: Use OCaml ${{ matrix.ocaml-version }}
        uses: ocaml/setup-ocaml@v3.4.1
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler}}

      - run: opam install libirmin
      
      - run: nix develop --command cargo build --release

      - run: nix develop --command cargo run --example json_merge
      - run: nix develop --command cargo run --example test_store
